### ISSUE TITLE
Can you enable https on your site.

### ISSUE THREAD

**Issue by vishnu667** [rabbanishah/NaturesCall#2]
Register your site on cloud-flare and serve the site through their CDN to enable https. [LINK](https://blog.cloudflare.com/introducing-universal-ssl/)

Console log from Browser

```
getCurrentPosition() and watchPosition() are deprecated on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
```

**Comment by KidEinstein** [comment]
Resolved! Thanks a lot for the suggestion.
